// Transcribed from the supplied organizer dataset. These are UI fixtures, not an engine.
import type { Analysis, Decision, District, Measure, Simulation } from './types';
export const districts: District[] = [
  {
    id: 'esil',
    name: 'Есиль',
    populationShare: 0.27,
    profile: 'Развитый район: пробки на мостах и переполненные школы.',
    indicators: { T1: 45, T2: 62, E1: 68, E2: 72, S1: 48, S2: 55, B1: 78, B2: 60, C1: 75, C2: 70 },
    score: 62.99,
  },
  {
    id: 'almaty',
    name: 'Алматы',
    populationShare: 0.24,
    profile: 'Плотная городская среда, изношенные сети ЖКХ и пробки.',
    indicators: { T1: 40, T2: 75, E1: 50, E2: 55, S1: 60, S2: 65, B1: 62, B2: 52, C1: 50, C2: 60 },
    score: 57.06,
  },
  {
    id: 'saryarka',
    name: 'Сарыарка',
    populationShare: 0.2,
    profile: 'Смог от частного сектора и нехватка зелёных пространств.',
    indicators: { T1: 50, T2: 70, E1: 42, E2: 40, S1: 62, S2: 68, B1: 58, B2: 55, C1: 45, C2: 55 },
    score: 54.65,
  },
  {
    id: 'baikonur',
    name: 'Байконур',
    populationShare: 0.13,
    profile: 'Сбалансированный район с потенциалом для улучшений.',
    indicators: { T1: 52, T2: 68, E1: 55, E2: 50, S1: 58, S2: 60, B1: 52, B2: 58, C1: 55, C2: 58 },
    score: 56.63,
  },
  {
    id: 'nura',
    name: 'Нура',
    populationShare: 0.16,
    profile: 'Растущий район: особенно нужны школы, медицина и транспорт.',
    indicators: { T1: 55, T2: 40, E1: 45, E2: 65, S1: 38, S2: 35, B1: 55, B2: 50, C1: 60, C2: 50 },
    score: 49.18,
  },
];
export const measures: Measure[] = [
  {
    id: 'M1',
    name: 'Выделенные полосы для автобусов',
    category: 'transport',
    scope: 'district',
    cost: 18,
    lag: 2,
    effects: { T1: 6, T2: 9 },
    description: 'Более предсказуемые поездки на общественном транспорте.',
    notes: ['Несовместимо с M3 в любом районе.', 'Синергия с M2: T1 +2 в районе M1.'],
  },
  {
    id: 'M2',
    name: 'Умные светофоры',
    category: 'transport',
    scope: 'city',
    cost: 22,
    lag: 2,
    effects: { T1: 4, B2: 3 },
    description: 'Адаптивное управление движением во всём городе.',
    notes: ['Синергия с M1: T1 +2 в районе M1.'],
  },
  {
    id: 'M3',
    name: 'Линия ЛРТ / расширение',
    category: 'transport',
    scope: 'district',
    cost: 30,
    lag: 4,
    effects: { T1: 16, T2: 20, E2: 4 },
    description: 'Долгосрочная инвестиция в транспортную доступность.',
    notes: ['Несовместимо с M1 в любом районе.'],
  },
  {
    id: 'M4',
    name: 'Парк / сквер',
    category: 'ecology',
    scope: 'district',
    cost: 15,
    lag: 2,
    effects: { E1: 12, E2: 3, B1: 2 },
    description: 'Зелёное пространство для прогулок и отдыха рядом с домом.',
    notes: ['Несовместимо с M7 в одном районе: конфликт за участок.'],
  },
  {
    id: 'M5',
    name: 'Чистое топливо для частного сектора',
    category: 'ecology',
    scope: 'district',
    cost: 25,
    lag: 3,
    effects: { E2: 14, C1: 4 },
    description: 'Снижение загрязнения воздуха от частного отопления.',
    notes: ['Несовместимо с M13 в одном районе.', 'Синергия с M6: E2 +2 в районе M5.'],
  },
  {
    id: 'M6',
    name: 'Городская программа озеленения',
    category: 'ecology',
    scope: 'city',
    cost: 20,
    lag: 4,
    effects: { E1: 5, E2: 3 },
    description: 'Озеленение и ветрозащитные полосы для всех пяти районов.',
    notes: ['Синергия с M5: E2 +2 в районе M5.'],
  },
  {
    id: 'M7',
    name: 'Школа + детский сад',
    category: 'social',
    scope: 'district',
    cost: 24,
    lag: 3,
    effects: { S1: 16 },
    description: 'Модульное строительство там, где мест не хватает.',
    notes: ['Несовместимо с M4 в одном районе: конфликт за участок.'],
  },
  {
    id: 'M8',
    name: 'Центр семейного здоровья',
    category: 'social',
    scope: 'district',
    cost: 20,
    lag: 3,
    effects: { S2: 14 },
    description: 'Поликлиника и доступная первичная помощь рядом с жителями.',
    notes: [],
  },
  {
    id: 'M9',
    name: 'Дворовые спорт-хабы',
    category: 'social',
    scope: 'district',
    cost: 10,
    lag: 1,
    effects: { S1: 3, S2: 3, B1: 3 },
    description: 'Активные дворы для спорта, общения и здоровых привычек.',
    notes: [],
  },
  {
    id: 'M10',
    name: 'Освещение и камеры',
    category: 'safety',
    scope: 'district',
    cost: 12,
    lag: 1,
    effects: { B1: 12, B2: 2 },
    description: 'Расширение Safe City и освещение городских улиц.',
    notes: ['Синергия с M12: B1 +2 в районе M10.'],
  },
  {
    id: 'M11',
    name: 'Безопасные переходы и школьные зоны',
    category: 'safety',
    scope: 'district',
    cost: 10,
    lag: 1,
    effects: { B2: 12, T1: -2 },
    description: 'Безопасность пешеходов с компромиссом в скорости движения.',
    notes: ['Отрицательный побочный эффект: T1 −2 до учёта лага.'],
  },
  {
    id: 'M12',
    name: 'Цифровая платформа обращений',
    category: 'services',
    scope: 'city',
    cost: 14,
    lag: 1,
    effects: { C2: 5 },
    description: 'Единое окно для диалога жителей и городских служб.',
    notes: ['Синергия с M10: B1 +2 в районе M10.'],
  },
  {
    id: 'M13',
    name: 'Модернизация тепло- и водосетей',
    category: 'services',
    scope: 'district',
    cost: 28,
    lag: 4,
    effects: { C1: 18, E2: 2 },
    description: 'Обновление инфраструктуры для надёжного тепла и воды.',
    notes: ['Несовместимо с M5 в одном районе.'],
  },
  {
    id: 'M14',
    name: 'Аварийные бригады ЖКХ',
    category: 'services',
    scope: 'city',
    cost: 16,
    lag: 1,
    effects: { C1: 5, C2: 2 },
    description: 'Быстрая реакция на аварии и раннее оповещение жителей.',
    notes: [],
  },
];
export const exampleDecisions: Decision[] = [
  { measureId: 'M7', districtId: 'nura' },
  { measureId: 'M8', districtId: 'nura' },
  { measureId: 'M10', districtId: 'nura' },
  { measureId: 'M12' },
  { measureId: 'M5', districtId: 'saryarka' },
];
export const baseline: Simulation['before'] = {
  score: 52.55768,
  cityAverage: 56.8624,
  weakestDistrictId: 'nura',
  criticalCount: 2,
  districts,
};
// Literal reference response for the one organizer scenario. Never reused for other choices.
export const exampleResult: Simulation = {
  modelVersion: 'organizer-dataset-v1',
  scenarioId: 'fixture-official-example',
  source: 'fixture',
  decisions: exampleDecisions,
  validation: { status: 'valid', errors: [] },
  budget: { total: 100, spent: 95, remaining: 5 },
  before: baseline,
  after: {
    score: 56.54307,
    cityAverage: 58.0776,
    weakestDistrictId: 'nura',
    criticalCount: 0,
    districts: [
      { ...districts[0], score: 63.4275, indicators: { ...districts[0].indicators, C2: 74.375 } },
      { ...districts[1], score: 57.4975, indicators: { ...districts[1].indicators, C2: 64.375 } },
      {
        ...districts[2],
        score: 56.3,
        indicators: { ...districts[2].indicators, E2: 48.75, C1: 47.5, C2: 59.375 },
      },
      { ...districts[3], score: 57.0675, indicators: { ...districts[3].indicators, C2: 62.375 } },
      {
        ...districts[4],
        score: 52.9625,
        indicators: {
          ...districts[4].indicators,
          S1: 48,
          S2: 43.75,
          B1: 67.5,
          B2: 51.75,
          C2: 54.375,
        },
      },
    ],
  },
  scoreDelta: 3.98539,
  synergies: [
    {
      measureIds: ['M10', 'M12'],
      districtId: 'nura',
      description: 'Освещение + цифровые обращения: B1 +2 в Нуре.',
    },
  ],
  contributions: [],
  notice:
    'Контрольный пример организаторов. Сохранённый ответ для демонстрации интерфейса; сервер расчёта не подключён.',
};
export const exampleAnalysis: Analysis = {
  source: 'template',
  summary:
    'План направляет основные вложения в социальную инфраструктуру Нуры, улучшает безопасность и снижает загрязнение воздуха в Сарыарке. Все критические показатели исходного набора выходят из зоны ниже 40.',
  strengths: [
    'Школа и поликлиника закрывают два критических дефицита Нуры.',
    'Освещение и платформа обращений создают синергию безопасности.',
  ],
  risks: ['Нура остаётся самым слабым районом.', 'Транспортная доступность Нуры не улучшается.'],
  tradeoffs: [
    'Приоритет социальной сферы оставляет транспорт без вложений.',
    'У строительства школы и поликлиники есть задержка в три квартала.',
  ],
  recommendations: [
    'Сравните этот план с вариантом, включающим общественный транспорт.',
    'Оцените баланс улучшений между Нурой и остальными районами.',
  ],
};
